In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Dataset/world_energy_consumption.csv')
df.head()
pd.set_option('display.precision', 2) #2 decimal points value only

### 1. EDA

In [4]:
print("Dataset dimension (R,C)", df.shape)
print("Columns", df.columns.values)
# print(df.info)

Dataset dimension (R,C) (21989, 129)
Columns ['country' 'year' 'iso_code' 'population' 'gdp' 'biofuel_cons_change_pct'
 'biofuel_cons_change_twh' 'biofuel_cons_per_capita' 'biofuel_consumption'
 'biofuel_elec_per_capita' 'biofuel_electricity' 'biofuel_share_elec'
 'biofuel_share_energy' 'carbon_intensity_elec' 'coal_cons_change_pct'
 'coal_cons_change_twh' 'coal_cons_per_capita' 'coal_consumption'
 'coal_elec_per_capita' 'coal_electricity' 'coal_prod_change_pct'
 'coal_prod_change_twh' 'coal_prod_per_capita' 'coal_production'
 'coal_share_elec' 'coal_share_energy' 'electricity_demand'
 'electricity_generation' 'electricity_share_energy'
 'energy_cons_change_pct' 'energy_cons_change_twh' 'energy_per_capita'
 'energy_per_gdp' 'fossil_cons_change_pct' 'fossil_cons_change_twh'
 'fossil_elec_per_capita' 'fossil_electricity' 'fossil_energy_per_capita'
 'fossil_fuel_consumption' 'fossil_share_elec' 'fossil_share_energy'
 'gas_cons_change_pct' 'gas_cons_change_twh' 'gas_consumption'
 'gas_elec_per_capita' 'gas_electricity' 'gas_energy_per_capita'
 'gas_prod_change_pct' 'gas_prod_change_twh' 'gas_prod_per_capita'
 'gas_production' 'gas_share_elec' 'gas_share_energy'
 'greenhouse_gas_emissions' 'hydro_cons_change_pct'
 'hydro_cons_change_twh' 'hydro_consumption' 'hydro_elec_per_capita'
 'hydro_electricity' 'hydro_energy_per_capita' 'hydro_share_elec'
 'hydro_share_energy' 'low_carbon_cons_change_pct'
 'low_carbon_cons_change_twh' 'low_carbon_consumption'
 'low_carbon_elec_per_capita' 'low_carbon_electricity'
 'low_carbon_energy_per_capita' 'low_carbon_share_elec'
 'low_carbon_share_energy' 'net_elec_imports'
 'net_elec_imports_share_demand' 'nuclear_cons_change_pct'
 'nuclear_cons_change_twh' 'nuclear_consumption' 'nuclear_elec_per_capita'
 'nuclear_electricity' 'nuclear_energy_per_capita' 'nuclear_share_elec'
 'nuclear_share_energy' 'oil_cons_change_pct' 'oil_cons_change_twh'
 'oil_consumption' 'oil_elec_per_capita' 'oil_electricity'
 'oil_energy_per_capita' 'oil_prod_change_pct' 'oil_prod_change_twh'
 'oil_prod_per_capita' 'oil_production' 'oil_share_elec'
 'oil_share_energy' 'other_renewable_consumption'
 'other_renewable_electricity' 'other_renewable_exc_biofuel_electricity'
 'other_renewables_cons_change_pct' 'other_renewables_cons_change_twh'
 'other_renewables_elec_per_capita'
 'other_renewables_elec_per_capita_exc_biofuel'
 'other_renewables_energy_per_capita' 'other_renewables_share_elec'
 'other_renewables_share_elec_exc_biofuel' 'other_renewables_share_energy'
 'per_capita_electricity' 'primary_energy_consumption'
 'renewables_cons_change_pct' 'renewables_cons_change_twh'
 'renewables_consumption' 'renewables_elec_per_capita'
 'renewables_electricity' 'renewables_energy_per_capita'
 'renewables_share_elec' 'renewables_share_energy' 'solar_cons_change_pct'
 'solar_cons_change_twh' 'solar_consumption' 'solar_elec_per_capita'
 'solar_electricity' 'solar_energy_per_capita' 'solar_share_elec'
 'solar_share_energy' 'wind_cons_change_pct' 'wind_cons_change_twh'
 'wind_consumption' 'wind_elec_per_capita' 'wind_electricity'
 'wind_energy_per_capita' 'wind_share_elec' 'wind_share_energy']

In [5]:
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,4.71e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,4.75e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,4.80e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,4.86e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,4.92e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.drop("iso_code", axis=1) #axis = 0(for dropping using index), 1(for dropping using columns)

,country,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,4.71e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,4.75e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,4.80e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,4.86e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,4.92e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21984,Zimbabwe,2018,1.51e+07,2.27e+10,NaN,NaN,NaN,NaN,25.91,0.39,...,0.22,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
21985,Zimbabwe,2019,1.54e+07,NaN,NaN,NaN,NaN,NaN,24.75,0.38,...,0.36,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
21986,Zimbabwe,2020,1.57e+07,NaN,NaN,NaN,NaN,NaN,22.34,0.35,...,0.40,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
21987,Zimbabwe,2021,1.60e+07,NaN,NaN,NaN,NaN,NaN,23.76,0.38,...,0.50,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
21988,Zimbabwe,2022,1.63e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['country'].unique() # getting unique values i.e. name of every country in country column

array(['Afghanistan', 'Africa', 'Africa (EI)', 'Africa (Ember)',
       'Africa (Shift)', 'Albania', 'Algeria', 'American Samoa', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Aruba', 'Asia', 'Asia & Oceania (EIA)', 'Asia (Ember)',
       'Asia Pacific (EI)', 'Asia and Oceania (Shift)', 'Australia',
       'Australia and New Zealand (EIA)', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS (EI)', 'Cambodia', 'Cameroon', 'Canada',
       'Cape Verde', 'Cayman Islands', 'Central & South America (EIA)',
       'Central African Republic', 'Central America (EI)',
       'Central and South America (Shift)', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       'Czechoslovakia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'EU28 (Shift)',
       'East Germany (EIA)', 'East Timor', 'Eastern Africa (EI)',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Eurasia (EIA)',
       'Eurasia (Shift)', 'Europe', 'Europe (EI)', 'Europe (Ember)',
       'Europe (Shift)', 'European Union (27)', 'European Union (EIA)',
       'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France',
       'French Guiana', 'French Polynesia', 'G20 (Ember)', 'G7 (Ember)',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Hawaiian Trade Zone (EIA)', 'High-income countries', 'Honduras',
       'Hong Kong', 'Hungary', 'IEO - Africa (EIA)',
       'IEO - Middle East (EIA)', 'IEO OECD - Europe (EIA)', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latin America and Caribbean (Ember)', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Low-income countries',
       'Lower-middle-income countries', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico',
       'Mexico, Chile, and other OECD Americas (EIA)',
       'Micronesia (country)', 'Middle Africa (EI)', 'Middle East (EI)',
       'Middle East (EIA)', 'Middle East (Ember)', 'Middle East (Shift)',
       'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'Non-OECD (EI)', 'Non-OECD (EIA)', 'Non-OPEC (EI)',
       'Non-OPEC (EIA)', 'North America', 'North America (EI)',
       'North America (Ember)', 'North America (Shift)', 'North Korea',
       'North Macedonia', 'Northern Mariana Islands', 'Norway',
       'OECD (EI)', 'OECD (EIA)', 'OECD (Ember)', 'OECD (Shift)',
       'OECD - Asia And Oceania (EIA)', 'OECD - Europe (EIA)',
       'OECD - North America (EIA)', 'OPEC (EI)', 'OPEC (EIA)',
       'OPEC (Shift)', 'OPEC - Africa (EIA)',
       'OPEC - South America (EIA)', 'Oceania', 'Oceania (Ember)', 'Oman',
       'Other Non-OECD - America (EIA)', 'Other Non-OECD - Asia (EIA)',
       'Other Non-OECD - Europe and Eurasia (EIA)', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Persian Gulf (EIA)', 'Persian Gulf (Shift)', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone',
       'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South America', 'South Korea',
       'South Korea and other OECD Asia (EIA)', 'South Sudan',
       'South and Central America (EI)', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'U.S. Pacific Islands (EIA)',
       'U.S. Territories (EIA)', 'USSR', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Pacific Islands (Shift)',
       'United States Territories (Shift)',
       'United States Virgin Islands', 'Upper-middle-income countries',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wake Island (EIA)', 'Wake Island (Shift)', 'West Germany (EIA)',
       'Western Africa (EI)', 'Western Sahara', 'World', 'Yemen',
       'Yugoslavia', 'Zambia', 'Zimbabwe'], dtype=object)